/**
 * Full-pipeline parity with R seminr 2.6.0 on the textbook corporate
 * reputation model (four formative, three reflective, one single-item
 * construct): estimation summary tables and PLSpredict.
 *
 * Ground truth in test/fixtures-r-extended-model.txt, generated by
 * test/fixtures.R (R 4.6.0, seminr 2.6.0). Bootstrap intervals are NOT
 * compared: seminr's bootstrap draws on a parallel RNG stream, so they agree
 * only to Monte Carlo error. PLSpredict IS compared exactly, because the
 * fold shuffle is R's sample() under set.seed(123), reproduced by rrng.ts.
 *
 * Run:  npx tsx test/seminr-parity.mjs
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { runAnalysis } from "../src/lib/seminr/analyze.ts";
import { parseSeminrModel } from "../src/lib/seminr/parseSeminr.ts";
import { parseDataText } from "../src/lib/seminr/data.ts";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
let failures = 0;
const check = (label, ok, detail = "") => {
  console.log(`${ok ? "  PASS" : "  FAIL"}  ${label}${detail ? ` — ${detail}` : ""}`);
  if (!ok) failures++;
};

// --- fixture reader ----------------------------------------------------------
const fixture = fs.readFileSync(path.join(root, "test", "fixtures-r-extended-model.txt"), "utf8");
function block(name) {
  const re = new RegExp(`^${name} \\n([\\s\\S]*?)^END`, "m");
  const m = re.exec(fixture);
  if (!m) throw new Error(`fixture block ${name} not found`);
  const rows = {};
  for (const line of m[1].trim().split("\n")) {
    const [r, ...vals] = line.split("|").map((s) => s.trim());
    rows[r] = vals.map((v) => (v === "NA" ? NaN : Number(v)));
  }
  return rows;
}
const relDiff = (a, b) => (Number.isNaN(a) && Number.isNaN(b)) ? 0 : Math.abs(a - b) / Math.max(Math.abs(b), 1e-8);
function compareMatrix(label, m, truth, tol = 1e-9, rowsToCheck = Object.keys(truth)) {
  let worst = 0, at = "";
  for (const r of rowsToCheck) {
    const i = m.rows.indexOf(r);
    if (i < 0) { check(`${label}: row ${r} present`, false); continue; }
    truth[r].forEach((t, j) => {
      const d = relDiff(m.values[i][j], t);
      if (d > worst) { worst = d; at = `${r}[${m.cols[j]}] got ${m.values[i][j]} want ${t}`; }
    });
  }
  check(`${label} matches R (< ${tol} relative)`, worst < tol, `worst ${worst.toExponential(2)} ${at}`);
}

// --- parser coverage of the extended syntax ---------------------------------
console.log("\nSEMinR parser: extended syntax");
{
  const m = parseSeminrModel(`
    library(seminr)
    mm <- constructs(
      composite("A", multi_items("a_", 1:3), weights = mode_B),
      composite("B", multi_items("b_", c(1, 3, 5), prefix = "x", suffix = "y")),
      reflective("C", multi_items("c_", 1:2)),
      composite("D", c("d1", "d2"), unit_weights),
      composite("E", single_item("e")),
      higher_composite("H", dimensions = c("A", "B"), method = two_stage, weights = mode_B),
      interaction_term(iv = "C", moderator = "D", method = two_stage),
      quadratic_term(iv = "C")
    )
    sm <- relationships(paths(from = c("H", "C", "D", "C*D", "C*C"), to = "E"), paths("A", "C"))
    model <- estimate_pls(data = d, measurement_model = mm, structural_model = sm)  # ignored
  `);
  check("8 measurement entries", m.measurement.length === 8, String(m.measurement.length));
  check("mode_B weights", m.measurement[0].weights === "mode_B");
  check("multi_items affixes", m.measurement[1].items.join(",") === "xb_1y,xb_3y,xb_5y", m.measurement[1].items.join(","));
  check("reflective flagged", m.measurement[2].reflective === true);
  check("raw c() items + positional unit_weights", m.measurement[3].items.length === 2 && m.measurement[3].weights === "unit_weights");
  check("higher_composite parsed", m.measurement[5].kind === "higher_composite" && m.measurement[5].dimensions.length === 2 && m.measurement[5].weights === "mode_B");
  check("interaction_term named iv*moderator", m.measurement[6].name === "C*D" && m.measurement[6].method === "two_stage");
  check("quadratic_term named iv*iv", m.measurement[7].name === "C*C" && m.measurement[7].quadratic === true);
  check("positional paths(from, to)", m.paths[1].from[0] === "A" && m.paths[1].to[0] === "C");

  const bad = [
    ['constructs(composite("A", multi_items("a_",1:3)), composite("B", single_item("b"), weights = mode_B))\nrelationships(paths("A","B"))', /single-item/],
    ['constructs(composite("A", multi_items("a_",1:3)), composite("A", multi_items("b_",1:3)))\nrelationships(paths("A","A"))', /defined twice/],
    ['constructs(composite("A", multi_items("a_",1:3)), composite("B", multi_items("b_",1:3)))\nrelationships(paths("A","A"))', /cannot predict itself/],
    ['constructs(composite("A", multi_items("a_",1:3)), higher_composite("H", dimensions = c("A","Z")))\nrelationships(paths("A","H"))', /not a first-order construct/],
    ['constructs(composite("A", multi_items("a_",1:3)), composite("B", multi_items("b_",1:3), weights = mode_Z))\nrelationships(paths("A","B"))', /unrecognised weights/],
  ];
  bad.forEach(([src, re], i) => {
    let msg = "";
    try { parseSeminrModel(src); } catch (e) { msg = e.message; }
    check(`error case ${i + 1} rejected`, re.test(msg), msg.slice(0, 70));
  });
}

// --- data parsing -------------------------------------------------------------
console.log("\nData parsing");
{
  const tsv = parseDataText("a\tb\n1\t2\n3\tNA\n5\t6");
  check("tab-separated with NA", tsv.delimiter === "\t" && Number.isNaN(tsv.data.values[1][1]));
  const semi = parseDataText("a;b\n1,5;2\n3;4\n5;6");
  check("semicolon with decimal comma", semi.data.values[0][0] === 1.5);
  const quoted = parseDataText('"a","b"\n1,2\n3,4\n5,x');
  check("quoted header, non-numeric flagged", quoted.data.columns[0] === "a" && quoted.nonNumeric.includes("b"));
  let msg = "";
  try { parseDataText("a,b\n1,2,3\n4,5"); } catch (e) { msg = e.message; }
  check("ragged row rejected", /Row 1 has 3 cells/.test(msg), msg);
}

// --- pipeline parity with R ---------------------------------------------------
console.log("\nEstimation summary vs R seminr 2.6.0 (corporate reputation, extended model)");
const dataText = fs.readFileSync(path.join(root, "public", "seminr-demo", "corp_rep_data.csv"), "utf8");
const CODE = `mm <- constructs(
  composite("QUAL", multi_items("qual_", 1:8), weights = mode_B),
  composite("PERF", multi_items("perf_", 1:5), weights = mode_B),
  composite("CSOR", multi_items("csor_", 1:5), weights = mode_B),
  composite("ATTR", multi_items("attr_", 1:3), weights = mode_B),
  composite("COMP", multi_items("comp_", 1:3)),
  composite("LIKE", multi_items("like_", 1:3)),
  composite("CUSA", single_item("cusa")),
  composite("CUSL", multi_items("cusl_", 1:3)))
sm <- relationships(
  paths(from = c("QUAL","PERF","CSOR","ATTR"), to = c("COMP","LIKE")),
  paths(from = c("COMP","LIKE"), to = c("CUSA","CUSL")),
  paths(from = "CUSA", to = "CUSL"))`;

const res = await runAnalysis({
  code: CODE, dataText, dataName: "corp_rep_data.csv",
  options: {
    estimation: { innerWeights: "path_weighting", missing: "mean_replacement", missingValue: -99 },
    bootstrap: { enabled: true, nboot: 60, seed: 123, alpha: 0.05 },
    predict: { enabled: true, noFolds: 10, technique: "predict_DA", seed: 123, cvpat: false, cvpatNboot: 0 },
    congruence: { enabled: false, nboot: 0, seed: 123, alpha: 0.05, threshold: 1, diagonal: "rhoA" },
  },
});

compareMatrix("paths (R², adj. R², coefficients)", res.summary.paths, block("PATHS"));
compareMatrix("reliability (alpha, rhoA, rhoC, AVE)", res.summary.reliability, block("RELIABILITY"));
compareMatrix("HTMT (lower triangle)", res.summary.validity.htmt, block("HTMT"));
compareMatrix("f² effect sizes", res.summary.fSquare, block("FSQUARE"), 1e-8);
{
  const truth = block("VIF_ANTECEDENTS_CUSL");
  let worst = 0;
  for (const [iv, [v]] of Object.entries(truth)) worst = Math.max(worst, relDiff(res.summary.vifAntecedents.CUSL[iv], v));
  check("antecedent VIFs match R", worst < 1e-9, `worst ${worst.toExponential(2)}`);
}

console.log("\nPLSpredict vs R (set.seed(123); predict_pls(noFolds = 10))");
compareMatrix("PLS out-of-sample RMSE/MAE", res.predict.plsOutOfSample, block("PLS_OOS"), 1e-8);
compareMatrix("LM out-of-sample RMSE/MAE", res.predict.lmOutOfSample, block("LM_OOS"), 1e-8);
compareMatrix("PLS in-sample RMSE", res.predict.plsInSample, block("PLS_IS"), 1e-8, ["RMSE"]);

console.log("\nBootstrap and derived stages");
{
  const b = res.bootstrap;
  check("bootstrap summary present", b && b.nboot === 60, String(b?.nboot));
  check("bootstrapped paths cover every structural path",
    b.bootstrappedPaths.rows.length === res.model.paths.length, `${b.bootstrappedPaths.rows.length} vs ${res.model.paths.length}`);
  check("bootstrap is reproducible for a seed", await (async () => {
    const again = await runAnalysis({ code: CODE, dataText, options: { ...res.input.options, predict: { ...res.input.options.predict, enabled: false } } });
    return JSON.stringify(again.bootstrap.bootstrappedPaths) === JSON.stringify(b.bootstrappedPaths);
  })());
  check("shared-pass bootstrap equals @seminr/core's bootstrapModel on the same resamples", await (async () => {
    const { bootstrapModel, summarizePlsBoot } = await import("@seminr/core");
    const { parseSeminrModel: parse } = await import("../src/lib/seminr/parseSeminr.ts");
    const { parseDataText: pd, selectColumns } = await import("../src/lib/seminr/data.ts");
    const { estimateParsedModel } = await import("../src/lib/seminr/specify.ts");
    const { rResampleIndices } = await import("../src/lib/seminr/bootstrap.ts");
    const parsed = parse(CODE);
    const data = selectColumns(pd(dataText).data, parsed.measurement.flatMap((m) => m.items ?? []));
    const model = estimateParsedModel(parsed, data, res.input.options.estimation);
    const idx = rResampleIndices(model.rawdata.values.length, 60, 123);
    const ref = summarizePlsBoot(bootstrapModel({ model, nboot: 60, indices: idx }), 0.05);
    return JSON.stringify(ref.bootstrappedPaths) === JSON.stringify(b.bootstrappedPaths) && JSON.stringify(ref.bootstrappedHtmt) === JSON.stringify(b.bootstrappedHtmt);
  })());
  check("congruence from the shared pass equals the standalone congruence test", await (async () => {
    const { congruenceFromModel } = await import("../src/lib/seminr/congruence.ts");
    const { parseSeminrModel: parse } = await import("../src/lib/seminr/parseSeminr.ts");
    const { parseDataText: pd, selectColumns } = await import("../src/lib/seminr/data.ts");
    const { estimateParsedModel } = await import("../src/lib/seminr/specify.ts");
    const parsed = parse(CODE);
    const data = selectColumns(pd(dataText).data, parsed.measurement.flatMap((m) => m.items ?? []));
    const model = estimateParsedModel(parsed, data, res.input.options.estimation);
    const fusedRun = await runAnalysis({ code: CODE, dataText, options: { ...res.input.options, predict: { ...res.input.options.predict, enabled: false }, congruence: { enabled: true, nboot: 40, seed: 123, alpha: 0.1, threshold: 1, diagonal: "rhoC" } } });
    const standalone = congruenceFromModel(model, model.rawdata, { nboot: 40, seed: 123, alpha: 0.1, threshold: 1, diagonal: "rhoC" });
    return JSON.stringify(fusedRun.congruence.rows) === JSON.stringify(standalone.rows) && fusedRun.timingsMs.congruence === undefined;
  })());
  check("mediation chains enumerated", res.mediation.specific.length > 0 && res.mediation.totalIndirect.length === 10, String(res.mediation.specific.length));
  check("assessment produced", res.assessment.length > 50 && res.assessment.every((a) => a.source));
  check("R script mentions every construct", res.model.constructs.every((c) => res.rScript.includes(`"${c.name}"`)));
  check("result is JSON-serialisable", JSON.parse(JSON.stringify(res)).schemaVersion === 1);
  check("DOT graphs present", res.model.dot.startsWith("digraph") && res.model.dotBoot.startsWith("digraph"));
  check("epistemic rho on every multi-item construct, in [0, 1]",
    res.model.constructs.filter((c) => c.items.length > 1).every((c) => c.epistemicRho > 0 && c.epistemicRho <= 1 + 1e-12));
  check("mode A epistemic rho is near 1 (score ≈ first principal component)",
    res.model.constructs.filter((c) => c.class === "reflective").every((c) => c.epistemicRho > 0.95));
  check("PLSpredict key target defaults to the final outcome", res.predict.keyTarget === "CUSL", res.predict.keyTarget);
  check("naive RMSE equals the indicator SD after mean replacement (population)", (() => {
    const it = "cusl_1";
    const col = parseDataText(dataText).data.columns.indexOf(it);
    const raw = parseDataText(dataText).data.values.map((r) => r[col]);
    const seen = raw.filter((v) => v !== -99);
    const fill = seen.reduce((a, b) => a + b, 0) / seen.length;
    const y = raw.map((v) => (v === -99 ? fill : v));
    const m = y.reduce((a, b) => a + b, 0) / y.length;
    const sd = Math.sqrt(y.reduce((a, b) => a + (b - m) ** 2, 0) / y.length);
    return Math.abs(sd - res.predict.naiveRmse[it]) < 1e-9;
  })());
  check("mediation chains carry a Zhao typology", res.mediation.specific.every((e) => ["complementary", "competitive", "indirect-only", "direct-only", "no effect"].includes(e.type)));
  check("evaluator digest carries aggregates only", await (async () => {
    const { buildDigest, digestLooksSafe } = await import("../src/lib/seminr/digest.ts");
    const cols = parseDataText(dataText).data.columns;
    const d = buildDigest(res, cols, "test");
    const text = JSON.stringify(d);
    const aRow = dataText.split("\n")[5].trim();
    return digestLooksSafe(d) && !text.includes(aRow) && !text.includes("compositeScores") && text.length < 60000 && d.availableColumns.includes("qual_global") && d.paths.length === res.model.paths.length;
  })());
  check("hostile construct names are escaped everywhere they are rendered", await (async () => {
    const { renderSections, renderStandaloneReport } = await import("../src/lib/seminr/report.ts");
    const { buildDigest } = await import("../src/lib/seminr/digest.ts");
    const evil = '<img src=x onerror=alert(1)>';
    const code = `mm <- constructs(composite("${evil}", multi_items("comp_", 1:3)), composite("LIKE", multi_items("like_", 1:3)), composite("CUSA", single_item("cusa")))\nsm <- relationships(paths(from = c("${evil}", "LIKE"), to = "CUSA"))`;
    const r = await runAnalysis({ code, dataText, options: { ...res.input.options, bootstrap: { ...res.input.options.bootstrap, nboot: 50 }, predict: { ...res.input.options.predict, enabled: true, cvpat: false }, congruence: { ...res.input.options.congruence, enabled: true, nboot: 50 } } });
    const html = renderSections(r, { tsv: {} }).map((s) => s.html).join("") + renderStandaloneReport(r, { tsv: {} });
    const rendered = html.replace(/<pre class="code"><code>[\s\S]*?<\/code><\/pre>/g, ""); // code blocks are escaped separately
    const digest = JSON.stringify(buildDigest(r, [evil, "x"]));
    return !/<img/i.test(rendered) && rendered.includes("&lt;img") && !/<img/i.test(html.replace(/&lt;img/g, "")) && digest.includes(evil) && r.model.dot.includes("alert(1)") === true;
  })());
  check("parser refuses oversized code, ranges and item counts", (() => {
    const errs = [];
    for (const src of [
      "x".repeat(100_001),
      'constructs(composite("A", multi_items("a_", 1:5000)), composite("B", single_item("b")))\nrelationships(paths("A","B"))',
      'constructs(' + Array.from({ length: 3 }, (_, k) => `composite("C${k}", multi_items("c${k}_", 1:1999))`).join(", ") + ')\nrelationships(paths("C0","C1"))',
    ]) { try { parseSeminrModel(src); errs.push("no error"); } catch (e) { errs.push(e.message); } }
    return /too long/.test(errs[0]) && /too large/.test(errs[1]) && /limit is 5000/.test(errs[2]);
  })());
  check("assessment splits gates from findings",
    res.assessment.some((a) => a.kind === "gate") && res.assessment.some((a) => a.kind === "finding") && res.assessment.filter((a) => a.kind === "finding").every((a) => a.status === "info"));
}

console.log(failures === 0 ? "\nAll seminr pipeline checks passed.\n" : `\n${failures} check(s) FAILED.\n`);
process.exit(failures === 0 ? 0 : 1);
